export enum PageEnum {
    ROOT = '/',
    INICIO = '/',
    BIENVENIDA = '/bienvenida',
    EVENTOS = '/eventos',
    BASE_NEGOCIO = '/negocio',
    VER_NEGOCIO = 'VerNegocio',
    NEGOCIO_INFORMACION_GENERAL = 'NegocioInformacionGeneral',
    NEGOCIO_EVENTOS = 'NegocioEventos',
    ADD_NEGOCIO = 'AddNegocio',
    BUSCAR_NEGOCIO = 'BuscarNegocio',
    LOGIN = '/login',
    REGISTRO = '/signup',
    PAGINA_ERROR = '/exception',
}
