[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "front/" # Directorio base donde se encuentra el proyecto frontend.
  publish = "front/dist/" # Directorio donde se generan los archivos construidos.
  command = "npm install && npm run build" # Comando para construir el proyecto.
